# Generated by Django 4.1.1 on 2022-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='latitude',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='longitude',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
