# Generated by Django 4.1.1 on 2022-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_userdetail_latitude_userdetail_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('response', models.CharField(default='none', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='request',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
