# Generated by Django 4.1.1 on 2022-10-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0004_rename_request_userdetail_requested'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mechanic',
            new_name='vmechanic',
        ),
    ]
